// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyXGMGupVCh1PXfItzQ1TvqQGBVJvTOdk',
    appId: '1:92260348975:web:5dee721d417c300c7e82da',
    messagingSenderId: '92260348975',
    projectId: 'cobro-65a79',
    authDomain: 'cobro-65a79.firebaseapp.com',
    databaseURL: 'https://cobro-65a79.firebaseio.com',
    storageBucket: 'cobro-65a79.appspot.com',
    measurementId: 'G-JZLJXBE4M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACpTNqPLw_hLKtuWDU26xKaCZ6px8Srds',
    appId: '1:92260348975:android:cf81612e174dcde87e82da',
    messagingSenderId: '92260348975',
    projectId: 'cobro-65a79',
    databaseURL: 'https://cobro-65a79.firebaseio.com',
    storageBucket: 'cobro-65a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS2MDF9QOd0v55BNgaFgupPX-6II3XHKI',
    appId: '1:92260348975:ios:9b7f06429cb406aa7e82da',
    messagingSenderId: '92260348975',
    projectId: 'cobro-65a79',
    databaseURL: 'https://cobro-65a79.firebaseio.com',
    storageBucket: 'cobro-65a79.appspot.com',
    androidClientId: '92260348975-l85m9p7nbnrv5iqdojpee4q1ppetk7l2.apps.googleusercontent.com',
    iosClientId: '92260348975-ddnfn5ba59v56dl0ghgim3dpm6f3cs5c.apps.googleusercontent.com',
    iosBundleId: 'com.uranodev.finanzapp.cobroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS2MDF9QOd0v55BNgaFgupPX-6II3XHKI',
    appId: '1:92260348975:ios:9b7f06429cb406aa7e82da',
    messagingSenderId: '92260348975',
    projectId: 'cobro-65a79',
    databaseURL: 'https://cobro-65a79.firebaseio.com',
    storageBucket: 'cobro-65a79.appspot.com',
    androidClientId: '92260348975-l85m9p7nbnrv5iqdojpee4q1ppetk7l2.apps.googleusercontent.com',
    iosClientId: '92260348975-ddnfn5ba59v56dl0ghgim3dpm6f3cs5c.apps.googleusercontent.com',
    iosBundleId: 'com.uranodev.finanzapp.cobroApp',
  );
}
